Pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [

    path('', views.index, name = 'index'),

    path('menu', views.menu, name = 'menu'),

    path('menu/<int:pizza_id>/',views.pizza, name='pizza'),

    path('comment/<int:pizza_id>/',views.comment, name='comment'),

]

   
    

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)

    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete= models.CASCADE)
    topping_name = models.CharField(max_length=200)

    def __str__(self):
        return self.topping_name

pizzas/forms.py
from django import forms 
from .models import*

class toppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['topping_name']
        label = {'pizza_name':'Add a Comment'}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import *
import base64
from .forms import*

# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')



def menu(request):
    menu = Pizza.objects.all()
    context = {'all_pizzas':menu}
    return render(request, 'pizzas/menu.html', context)



def pizza(request, pizza_id):
    p = Pizza.objects.get(id=pizza_id)
    topping_name = Topping.objects.filter(pizza=p)
    if (pizza_id == 1):
        link = 'https://www.spam.com/wp-content/uploads/2019/09/image-recipe_spam-hawaiian-pizza-1000x500.jpg'
    elif (pizza_id == 2):
        link = 'https://www.pizzahut.com/c/assets/img/meat-lovers-pizza_875x300.jpg'
    elif (pizza_id == 3):
        link = 'https://www.foodandwine.com/thmb/Wd4lBRZz3X_8qBr69UOu2m7I2iw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/classic-cheese-pizza-FT-RECIPE0422-31a2c938fc2546c9a07b7011658cfd05.jpg'
    elif (pizza_id == 4):
        link = 'https://cdn.tasteatlas.com/images/dishes/b05a0af72ad845f3a6abe16143d7853a.jpg?mw=1300'
    else:
        link = 'https://www.tasteandtellblog.com/wp-content/uploads/2021/01/BBQ-Chicken-Pizza-3.jpg'
    context = {'pizza':p, 'topping_name':topping_name, 'link':link}
  
    return render(request, 'pizzas/pizza.html', context)

def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = toppingForm()
    else:
        print(request.POST)
        form = toppingForm(data=request.POST)
        if form.is_valid():
            newComment = form.save(commit = False)
            newComment.pizza = pizza
            newComment.save()
            return redirect('pizzas:pizza', pizza_id = pizza_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/comment.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}"style="color:#FF0000;font-family:verdana;">Home Page</a>
    <a href="{% url 'pizzas:menu' %}"style="color:#95e8f3;font-family:verdana;">  Menu</a>

</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}"> {{pizza}} </a></p>

<p> Add a comment</p>

<form action="{& url 'pizzas: comment' pizza.id%}" method = "post">

    {% csrf_token %}

    {{form.as_p}}


  <button name = "submit"> Add comment </button>

</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p style="text-align:center;"></p><img src="https://i.pinimg.com/originals/44/c0/49/44c0495d9bda8309fcfa207b6e848776.png" alt="Pizza"></p>


<p style="color:red;text-align:center;font-size:160%;font-family:verdana;"> Welcome to the pizzeria! </p>

<p style="color:#95e8f3;text-align:center;font-size:160%;font-family:verdana;"> Voted best pizza in the world! </p>

<p style="color:red;text-align:center;font-size:160%;font-family:verdana;"> Buy one large pizza get one 50% off </p>


{% endblock content %}

pizzas/templates/pizzas/menu.html
{% extends "pizzas/base.html" %}

{% block content %}

<p style="color:#95e8f3"> Menu </p>

<ul> 
    {% for pizza in all_pizzas %}
    <li>
      <!--  {{pizza}}-->
       <a href= "{% url 'pizzas:pizza' pizza.id %}" </a> {{pizza}}
    </li>    
    
        {% empty %}
        <li> No pizzas are available. </li> 
        {% endfor %}
    
</ul>



{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}


<p> Toppings on {{pizza}} Pizza</p>
<p style="text-align:center;"></p><img src=link alt="Pizza"></p>

<ul> 
    {% for topping in topping_name %}
    <li>{{ topping }} </li>    

        {% empty %}
        <li> No toppings for this pizza. </li> 
        {% endfor %}
    

        <p> 
            <a href="{% url 'pizzas:comment' pizza.id %}"></a>
        </p>
</ul>

{% endblock content %}